#!/bin/bash

killall opt_vsa 2>>/var/log/vsa/run_vsa.err
killall sign_control 2>>/var/log/vsa/run_vsa.err
killall xml_parser 2>>/var/log/vsa/run_vsa.err
killall clt_vars 2>>/var/log/vsa/run_vsa.err
killall db_slv 2>>/var/log/vsa/run_vsa.err
VSAPIDS=`ps -ef | grep -v grep | grep run_vsa | awk '{print $2}'`
if [[ q$VSAPIDS != 'q' ]]
then
	kill -9 $VSAPIDS
fi
/home/path/db/db_clean.sh 2>>/var/log/vsa/run_vsa.err
