install : run_vsa  safepace_retrieve_radar.php  safepace_set_speed.php  VSA.html
	cp run_vsa  safepace_retrieve_radar.php  safepace_set_speed.php  VSA.html /var/www/html/VSA/scripts
	sudo cp run_vsa kill_vsa /usr/local/bin
