#!/bin/bash

ps -elf | grep -v grep | grep db_slv
if [[ $? != 0 ]]
then
	/home/path/db/lnx/db_slv &
fi

ps -elf | grep -v grep | grep clt_vars
if [[ $? != 0 ]]
then
	/home/rfs-VSA/src/lnx/clt_vars &
fi

NOWTIME=`date +%s`
LATESTFILE=`ls -t /var/www/html/VSA/data/datafeed* | head -1` 2>/var/log/vsa/run_vsa.err
LATESTFILETIME=`stat -c %X $LATESTFILE` 2>>/var/log/vsa/run_vsa.err
TIMESINCELASTDATA=`echo $(($NOWTIME-$LATESTFILETIME))`

if [[ $TIMESINCELASTDATA -gt 7200 ]]
then
	echo Latest data is $TIMESINCELASTDATA seconds old. That is longer than 7200 seconds, so we are exiting....
	exit 0
fi

/home/rfs-VSA/src/lnx/xml_parser -f $LATESTFILE 2>>/var/log/vsa/run_vsa.err

#ps -elf | grep -v grep | grep opt_vsa
#if [[ $? != 0 ]]
#then
#	cd /home/rfs-VSA/src
#	./lnx/opt_vsa &
#fi
