#!/bin/bash

sudo killall opt_vsa
sudo killall sign_control
sudo killall xml_parser
sudo killall clt_vars
sudo killall db_slv

#Kill other run_vsa processes (it's run under a bash shell)
RUNVSAPIDS=`ps -ef | grep run_vsa | grep -v grep | awk '{print $2}'`
OTHERBASHPIDS=`pidof -o %PPID bash`
echo RUNVSAPIDS $RUNVSAPIDS OTHERBASHPIDS $OTHERBASHPIDS
for x in `echo $RUNVSAPIDS`
do 
	echo x $x
	echo $OTHERBASHPIDS | grep $x 
	if [[ $? -eq 0 ]] 
	then 
		echo "Im gonna kill $x"
		kill $x
	else 
		echo "Im not gonna kill $x"
		ps -ef | grep $x
fi
done

sudo /home/path/db/db_clean.sh

#Move Out_Data contents to a saved directory
NOW_TIME_SUFFIX=`date +%Y%m%d%H%M%S`
NOW_OUT_DIR="/linux2/big/data/VSA/Out_Data/Out_Data_"$NOW_TIME_SUFFIX
mkdir $NOW_OUT_DIR
mv /home/rfs-VSA/src/Out_Data/* $NOW_OUT_DIR

#Start everything back up
/home/path/db/lnx/db_slv &
sleep 1
/home/rfs-VSA/src/lnx/clt_vars &
sleep 1
cd /home/rfs-VSA/src
./lnx/sign_control &
sleep 1
./lnx/opt_vsa &

sleep 1
while [[ 1 ]]
do
	COUNTER=0
	TIMESINCELASTDATA=0
	while [[ ($TIMESINCELASTDATA -lt 5) && ($COUNTER -le 6) ]]
	do
		NOWTIME=`date +%s`
		date >>/var/log/vsa/run_vsa.err
		LATESTFILE=`ls -t /var/www/html/VSA/data/datafeed* | head -1` 2>>/var/log/vsa/run_vsa.err
		LATESTFILETIME=`stat -c %X $LATESTFILE` 2>>/var/log/vsa/run_vsa.err
		TIMESINCELASTDATA=`echo $(($NOWTIME-$LATESTFILETIME))`
		if [[ $TIMESINCELASTDATA -lt 5 ]]
		then
			COUNTER=$(($COUNTER+1))
			sleep 5
		fi
	done
	
	if [[ $TIMESINCELASTDATA -gt 7200 ]]
	then
		echo Latest data is $TIMESINCELASTDATA seconds old. That is longer than 7200 seconds, so we are exiting.... >>/var/log/vsa/run_vsa.err
		cd /var/www/html/VSA/webdata
		for x in `ls [123]*`
		do
			echo "Stale data" >$x
		done
		exit 0
	fi
	
	/home/rfs-VSA/src/lnx/xml_parser -f $LATESTFILE 2>>/var/log/vsa/run_vsa.err
	sleep 30
done
