#!/bin/bash

sudo killall opt_vsa
sudo killall xml_parser
sudo killall clt_vars
sudo killall db_slv
sudo /home/path/db/db_clean.sh

ps -elf | grep -v grep | grep db_slv
if [[ $? != 0 ]]
then
	/home/path/db/lnx/db_slv &
fi

ps -elf | grep -v grep | grep clt_vars
if [[ $? != 0 ]]
then
	/home/rfs-VSA/src/lnx/clt_vars &
fi

COUNTER=0
TIMESINCELASTDATA=0
while [[ ($TIMESINCELASTDATA -lt 5) && ($COUNTER -le 6) ]]
do
	NOWTIME=`date +%s`
	date >>/var/log/vsa/run_vsa.err
	LATESTFILE=`ls -t /var/www/html/VSA/data/datafeed* | head -1` 2>>/var/log/vsa/run_vsa.err
	LATESTFILETIME=`stat -c %X $LATESTFILE` 2>>/var/log/vsa/run_vsa.err
	TIMESINCELASTDATA=`echo $(($NOWTIME-$LATESTFILETIME))`
	if [[ $TIMESINCELASTDATA -lt 5 ]]
	then
		COUNTER=$(($COUNTER+1))
		sleep 5
	fi
done

if [[ $TIMESINCELASTDATA -gt 7200 ]]
then
	echo Latest data is $TIMESINCELASTDATA seconds old. That is longer than 7200 seconds, so we are exiting....
	exit 0
fi

/home/rfs-VSA/src/lnx/xml_parser -f $LATESTFILE 2>>/var/log/vsa/run_vsa.err

#ps -elf | grep -v grep | grep opt_vsa
#if [[ $? != 0 ]]
#then
#	cd /home/rfs-VSA/src
#	./lnx/opt_vsa &
#fi
