#!/bin/bash

NOWTIME=`date +%s`
cd /var/www/html/VSA
LATESTFILE=`ls -t /var/www/html/VSA | head -1`
LATESTFILETIME=`stat -c %X $LATESTFILE`
TIMESINCELASTDATA=`echo $(($NOWTIME-$LATESTFILETIME))`

if [[ $TIMESINCELASTDATA -gt 7200 ]]
then
	echo Latest data is $TIMESINCELASTDATA seconds old. That is longer than 7200 seconds, so we are exiting....
	exit 0
fi

killall xml_parser
killall db_slv
db_clean.sh
db_slv &

/home/rfs-VSA/src/lnx/xml_parser $LATESTFILE
